//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrachenwaldEventRegistration.Integration
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public System.Guid EventId { get; set; }
        public string EventName { get; set; }
        public System.DateTime RegistrationStart { get; set; }
        public System.DateTime RegistrationEnd { get; set; }
        public string AdminEmail { get; set; }
        public Nullable<System.DateTime> CancellationLastDate { get; set; }
        public string ContactInformation { get; set; }
        public int Year { get; set; }
    }
}
