//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrachenwaldEventRegistration.Integration
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public System.Guid RegistrationId { get; set; }
        public int RegistrationFormId { get; set; }
        public string RegistrationDetails { get; set; }
    }
}
