//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrachenwaldEventRegistration
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormItem
    {
        public int FormItemId { get; set; }
        public int Type { get; set; }
        public bool Mandatory { get; set; }
        public string DataValues { get; set; }
        public string LabelText { get; set; }
        public int CategoryId { get; set; }
    }
}
